# Nome do Workflow
name: OCI Terraform Pipeline

# Evento que irá acionar a pipeline (actions)
on: 
  push:
    branches:
      - main

jobs:
  Build:
    name: Build With Terraform
    runs-on: ubuntu-latest
    env:
      TF_VAR_tenancy_ocid: ${{secrets.OCI_TENANCY_ID}}
      TF_VAR_compartment_ocid: ${{secrets.OCI_COMPARTMENT_ID}}
      TF_VAR_user_ocid: ${{secrets.OCI_USER_ID}}
      TF_VAR_private_key: "~/.oci/oci_api_key.pem"
      TF_VAR_fingerprint: ${{secrets.OCI_FINGERPRINT}}
      TF_VAR_region: ${{secrets.OCI_REGION}}

    steps:
      - name: Write OCI Config File
        run: |
          mkdir ~/.oci
          touch ~/.oci/config
          echo "[DEFAULT]" >> ~/.oci/config
          echo "user=${{secrets.OCI_USER_ID}}" >> ~/.oci/config
          echo "fingerprint=${{secrets.}}" >> ~/.oci/config
          echo "tenancy=${{secrets.}}" >> ~/.oci/config
          echo "region=${{secrets.}}" >> ~/.oci/config
          echo "oci_username=${{secrets.OCI_USERNAME}}" >> ~/.oci/config
          echo "oci_user_authtoken=${{secrets.OCI_USER_AUTHTOKEN}}" >> ~/.oci/config
          echo "key_file=~/.oci/oci_api_key.pem" >> ~/.oci/config
          echo "To create the API signing key"
          openssl genrsa -out ~/.oci/oci_api_key.pem 2048
          chmod go-rwx ~/.oci/oci_api_key.pem
          echo "To generate the public key for the given private key"
          openssl rsa -pubout -in ~/.oci/oci_api_key.pem -out ~/.oci/oci_api_key_public.pem
          ls -ltr ~/.oci

      - name: Setup Terraform
      - uses: actions/checkout@v2
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -out config.tfplan
        continue-on-error: false

      - name: Terraform Apply
        id: apply
        run: terraform apply config.tfplan -auto-approve